:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  # Queue priority:
  # https://github.com/mperham/sidekiq/wiki/Advanced-Options
  - default
  - mailers

:schedule:
  LsTradesJob:
    every: '15m'
    queue: default
    enabled: true
  ProductDataJob:
    every: '2h'
    queue: default
    enabled: true
