:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  # Queue priority:
  # https://github.com/mperham/sidekiq/wiki/Advanced-Options
  - default
  - mailers

:schedule:
  LsTradesJob:
    every: "5m"
    queue: default
    enabled: true

  CurrencyExchangeRatesJob:
    every: "1d"
    queue: default
    enabled: true
  ProductDataJob:
    cron: '0 1 * * *'
    queue: default
    enabled: true
  StockDataJob:
    cron: '0 */6 * * *'
    queue: default
    enabled: true
