:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  # Queue priority:
  # https://github.com/mperham/sidekiq/wiki/Advanced-Options
  - default
  - mailers

:schedule:
  LsTradesJob:
    every: "15m"
    queue: default
    enabled: true

  CurrencyExchangeRatesJob:
    every: "1d"
    queue: default
    enabled: true
