:concurrency: 3
:timeout: 36000
:verbose: true
:queues:
  # Queue priority:
  # https://github.com/mperham/sidekiq/wiki/Advanced-Options
  - default
  - mailers
  - yahoo

:schedule:
  LsTradesJob:
    cron: "*/5 7-23 * * *"
    queue: default
    enabled: true
  CurrencyExchangeRatesJob:
    every: "1d"
    queue: yahoo
    enabled: true
  ProductDataJob:
    cron: "0 1 * * *"
    queue: yahoo
    enabled: true
  StockDataJob:
    cron: "30 */1 * * *"
    queue: yahoo
    enabled: true
